import { User, Unit, Exercise, LeaderboardEntry } from './types';

export const mockUser: User = {
  id: '1',
  name: 'Alexandre',
  email: 'alexandre@example.com',
  avatar: 'A',
  streak: 12,
  xp: 2450,
  gems: 340,
  hearts: 4,
  maxHearts: 5,
  level: 8,
  league: 'gold',
  weeklyXP: 580,
  badges: [
    { id: '1', name: 'Premier Pas', description: 'Premier exercice complété', icon: '🌟', color: '#F59E0B' },
    { id: '2', name: 'Semaine de Feu', description: '7 jours consécutifs', icon: '🔥', color: '#EF4444' },
    { id: '3', name: 'Vocabulaire Pro', description: '100 mots appris', icon: '📚', color: '#8B5CF6' },
    { id: '4', name: 'Oreille Fine', description: '50 exercices d\'écoute', icon: '👂', color: '#06B6D4' },
    { id: '5', name: 'Orateur', description: '25 exercices de prononciation', icon: '🎤', color: '#10B981' },
  ],
  languages: [
    { language: 'english', level: 'B1', xp: 2450, totalXP: 3000, wordsLearned: 342, streak: 12 },
    { language: 'spanish', level: 'A2', xp: 890, totalXP: 1500, wordsLearned: 128, streak: 5 },
    { language: 'portuguese', level: 'A1', xp: 210, totalXP: 750, wordsLearned: 34, streak: 2 },
  ],
};

export const englishUnits: Unit[] = [
  {
    id: 'u1',
    title: 'Greetings & Basics',
    titleFr: 'Salutations & Bases',
    icon: '👋',
    level: 'A1',
    color: '#10B981',
    description: 'Apprenez à vous présenter et à saluer en anglais',
    lessons: [
      { id: 'l1', unitId: 'u1', title: 'Hello & Goodbye', type: 'vocabulary', status: 'completed', xpReward: 10, duration: 5 },
      { id: 'l2', unitId: 'u1', title: 'My name is...', type: 'grammar', status: 'completed', xpReward: 15, duration: 7 },
      { id: 'l3', unitId: 'u1', title: 'Where are you from?', type: 'speaking', status: 'completed', xpReward: 20, duration: 8 },
      { id: 'l4', unitId: 'u1', title: 'Common Phrases', type: 'listening', status: 'completed', xpReward: 15, duration: 6 },
      { id: 'l5', unitId: 'u1', title: 'Mini Story', type: 'reading', status: 'completed', xpReward: 20, duration: 10 },
    ],
  },
  {
    id: 'u2',
    title: 'Numbers & Colors',
    titleFr: 'Chiffres & Couleurs',
    icon: '🔢',
    level: 'A1',
    color: '#F97316',
    description: 'Maîtrisez les chiffres et les couleurs fondamentaux',
    lessons: [
      { id: 'l6', unitId: 'u2', title: '1 to 100', type: 'vocabulary', status: 'completed', xpReward: 10, duration: 5 },
      { id: 'l7', unitId: 'u2', title: 'Counting Things', type: 'grammar', status: 'completed', xpReward: 15, duration: 7 },
      { id: 'l8', unitId: 'u2', title: 'Rainbow Colors', type: 'vocabulary', status: 'in_progress', xpReward: 10, duration: 5 },
      { id: 'l9', unitId: 'u2', title: 'Color Descriptions', type: 'reading', status: 'locked', xpReward: 15, duration: 8 },
      { id: 'l10', unitId: 'u2', title: 'Phone Numbers', type: 'listening', status: 'locked', xpReward: 20, duration: 10 },
    ],
  },
  {
    id: 'u3',
    title: 'Family & People',
    titleFr: 'Famille & Personnes',
    icon: '👨‍👩‍👧',
    level: 'A1',
    color: '#8B5CF6',
    description: 'Parlez de votre famille et des personnes autour de vous',
    lessons: [
      { id: 'l11', unitId: 'u3', title: 'My Family', type: 'vocabulary', status: 'locked', xpReward: 10, duration: 5 },
      { id: 'l12', unitId: 'u3', title: 'Possessives', type: 'grammar', status: 'locked', xpReward: 15, duration: 7 },
      { id: 'l13', unitId: 'u3', title: 'Family Descriptions', type: 'reading', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l14', unitId: 'u3', title: 'Family Conversations', type: 'listening', status: 'locked', xpReward: 15, duration: 8 },
      { id: 'l15', unitId: 'u3', title: 'Talk About Family', type: 'speaking', status: 'locked', xpReward: 25, duration: 12 },
    ],
  },
  {
    id: 'u4',
    title: 'Daily Routine',
    titleFr: 'Routine Quotidienne',
    icon: '☀️',
    level: 'A2',
    color: '#F59E0B',
    description: 'Décrivez votre journée type en anglais',
    lessons: [
      { id: 'l16', unitId: 'u4', title: 'Morning Activities', type: 'vocabulary', status: 'locked', xpReward: 15, duration: 7 },
      { id: 'l17', unitId: 'u4', title: 'Present Simple', type: 'grammar', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l18', unitId: 'u4', title: 'A Day in London', type: 'reading', status: 'locked', xpReward: 25, duration: 12 },
      { id: 'l19', unitId: 'u4', title: 'Morning News', type: 'listening', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l20', unitId: 'u4', title: 'My Daily Routine', type: 'speaking', status: 'locked', xpReward: 30, duration: 15 },
    ],
  },
  {
    id: 'u5',
    title: 'Food & Restaurants',
    titleFr: 'Nourriture & Restaurants',
    icon: '🍽️',
    level: 'A2',
    color: '#06B6D4',
    description: 'Commandez un repas et parlez de vos aliments préférés',
    lessons: [
      { id: 'l21', unitId: 'u5', title: 'Food Vocabulary', type: 'vocabulary', status: 'locked', xpReward: 15, duration: 7 },
      { id: 'l22', unitId: 'u5', title: 'I would like...', type: 'grammar', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l23', unitId: 'u5', title: 'A Restaurant Menu', type: 'reading', status: 'locked', xpReward: 25, duration: 12 },
      { id: 'l24', unitId: 'u5', title: 'At the Restaurant', type: 'listening', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l25', unitId: 'u5', title: 'Order Your Meal', type: 'speaking', status: 'locked', xpReward: 30, duration: 15 },
    ],
  },
  {
    id: 'u6',
    title: 'Travel & Transport',
    titleFr: 'Voyage & Transport',
    icon: '✈️',
    level: 'B1',
    color: '#EC4899',
    description: 'Planifiez et vivez vos voyages en anglais',
    lessons: [
      { id: 'l26', unitId: 'u6', title: 'Transport Words', type: 'vocabulary', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'l27', unitId: 'u6', title: 'Future Plans', type: 'grammar', status: 'locked', xpReward: 25, duration: 12 },
      { id: 'l28', unitId: 'u6', title: 'Travel Blog', type: 'reading', status: 'locked', xpReward: 30, duration: 15 },
      { id: 'l29', unitId: 'u6', title: 'Airport Announcements', type: 'listening', status: 'locked', xpReward: 25, duration: 12 },
      { id: 'l30', unitId: 'u6', title: 'Plan a Trip', type: 'speaking', status: 'locked', xpReward: 35, duration: 18 },
    ],
  },
];

export const spanishUnits: Unit[] = [
  {
    id: 'su1',
    title: 'Saludos y Básicos',
    titleFr: 'Salutations & Bases',
    icon: '👋',
    level: 'A1',
    color: '#10B981',
    description: 'Les premières bases de l\'espagnol',
    lessons: [
      { id: 'sl1', unitId: 'su1', title: 'Hola y Adiós', type: 'vocabulary', status: 'completed', xpReward: 10, duration: 5 },
      { id: 'sl2', unitId: 'su1', title: 'Me llamo...', type: 'grammar', status: 'completed', xpReward: 15, duration: 7 },
      { id: 'sl3', unitId: 'su1', title: 'Pronunciación', type: 'speaking', status: 'in_progress', xpReward: 20, duration: 8 },
      { id: 'sl4', unitId: 'su1', title: 'Frases Comunes', type: 'listening', status: 'locked', xpReward: 15, duration: 6 },
      { id: 'sl5', unitId: 'su1', title: 'Mini Historia', type: 'reading', status: 'locked', xpReward: 20, duration: 10 },
    ],
  },
  {
    id: 'su2',
    title: 'Ser y Estar',
    titleFr: 'Être (Ser vs Estar)',
    icon: '⚖️',
    level: 'A1',
    color: '#F97316',
    description: 'La différence cruciale entre ser et estar',
    lessons: [
      { id: 'sl6', unitId: 'su2', title: 'Ser Basics', type: 'grammar', status: 'locked', xpReward: 15, duration: 8 },
      { id: 'sl7', unitId: 'su2', title: 'Estar Basics', type: 'grammar', status: 'locked', xpReward: 15, duration: 8 },
      { id: 'sl8', unitId: 'su2', title: 'Ser vs Estar', type: 'reading', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'sl9', unitId: 'su2', title: 'Practice Dialogue', type: 'listening', status: 'locked', xpReward: 20, duration: 10 },
      { id: 'sl10', unitId: 'su2', title: 'Describing People', type: 'speaking', status: 'locked', xpReward: 25, duration: 12 },
    ],
  },
];

export const vocabularyExercises: Exercise[] = [
  {
    id: 'v1',
    type: 'vocabulary',
    question: 'Comment dit-on "pomme" en anglais ?',
    options: ['Orange', 'Apple', 'Banana', 'Grape'],
    correctAnswer: 'Apple',
    explanation: '"Apple" vient du vieil anglais "æppel". C\'est l\'un des mots les plus fondamentaux en anglais !',
    imageUrl: '🍎',
    xpReward: 10,
  },
  {
    id: 'v2',
    type: 'vocabulary',
    question: 'Que signifie "butterfly" en français ?',
    options: ['Abeille', 'Libellule', 'Papillon', 'Coccinelle'],
    correctAnswer: 'Papillon',
    explanation: '"Butterfly" — un mot poétique qui décrit cet insecte coloré qui vole gracieusement.',
    imageUrl: '🦋',
    xpReward: 10,
  },
  {
    id: 'v3',
    type: 'vocabulary',
    question: 'Sélectionnez la traduction correcte de "rain"',
    options: ['Neige', 'Nuage', 'Soleil', 'Pluie'],
    correctAnswer: 'Pluie',
    explanation: '"Rain" — la pluie en anglais. Souvenir : "It\'s raining cats and dogs !" = Il pleut des cordes !',
    imageUrl: '🌧️',
    xpReward: 10,
  },
];

export const grammarExercises: Exercise[] = [
  // ── A1 : To Be ──────────────────────────────────────────────────────
  {
    id: 'g1',
    type: 'grammar',
    question: 'Choisissez la forme correcte : "She ___ to school every day."',
    options: ['go', 'goes', 'going', 'gone'],
    correctAnswer: 'goes',
    explanation: 'Avec "she/he/it", on ajoute -s au verbe au présent simple. "She goes" est la forme correcte.',
    xpReward: 15,
  },
  {
    id: 'g2',
    type: 'grammar',
    question: 'Mettez les mots dans l\'ordre : [the / is / cat / sleeping / on / couch / the]',
    options: [
      'The sleeping cat is on the couch',
      'The cat is sleeping on the couch',
      'Is the cat sleeping the on couch',
      'On the couch the cat is sleeping',
    ],
    correctAnswer: 'The cat is sleeping on the couch',
    explanation: 'Structure: Sujet + be + verbe-ing + préposition + lieu. "The cat is sleeping on the couch" est parfaitement correct !',
    xpReward: 15,
  },
  {
    id: 'g3',
    type: 'grammar',
    question: 'Transformez en négatif : "I like coffee."',
    options: [
      "I don't like coffee.",
      "I not like coffee.",
      "I doesn't like coffee.",
      "I am not like coffee.",
    ],
    correctAnswer: "I don't like coffee.",
    explanation: 'Pour former le négatif avec "I", on utilise "don\'t" + infinitif. "I don\'t like coffee" est la bonne réponse.',
    xpReward: 15,
  },
  {
    id: 'g4',
    type: 'grammar',
    question: 'Complétez : "My name ___ Alex and I ___ from France."',
    options: ['is / am', 'am / is', 'are / am', 'is / are'],
    correctAnswer: 'is / am',
    explanation: '"My name IS" (he/she/it → is) et "I AM" (I → am). Chaque pronom a sa propre forme de "to be".',
    xpReward: 15,
  },
  {
    id: 'g5',
    type: 'grammar',
    question: 'Quel article est correct ? "___ apple is on the table."',
    options: ['A', 'An', 'The', 'One'],
    correctAnswer: 'An',
    explanation: 'On utilise "an" devant un son de voyelle. "Apple" commence par le son /æ/, donc c\'est "an apple".',
    xpReward: 15,
  },
  {
    id: 'g6',
    type: 'grammar',
    question: 'Pluriel correct de "child" ?',
    options: ['childs', 'childes', 'children', 'childrens'],
    correctAnswer: 'children',
    explanation: '"Children" est le pluriel irrégulier de "child". Il faut mémoriser les irréguliers : child/children, man/men, woman/women, tooth/teeth.',
    xpReward: 15,
  },
  // ── A1/A2 : Présent simple ───────────────────────────────────────────
  {
    id: 'g7',
    type: 'grammar',
    question: 'Question correcte au présent simple : "___ you speak English?"',
    options: ['Are', 'Do', 'Does', 'Is'],
    correctAnswer: 'Do',
    explanation: 'Pour former une question avec "you" au présent simple, on utilise "Do". "Does" s\'utilise avec he/she/it.',
    xpReward: 15,
  },
  {
    id: 'g8',
    type: 'grammar',
    question: 'Choisissez la bonne réponse : "He ___ his teeth every morning."',
    options: ['brush', 'brushes', 'is brushing', 'brushed'],
    correctAnswer: 'brushes',
    explanation: '"He" est un sujet 3ème personne du singulier → on ajoute -es (pas -s) après les verbes terminant par -sh, -ch, -s, -x, -o.',
    xpReward: 15,
  },
  {
    id: 'g9',
    type: 'grammar',
    question: 'Quelle phrase est correcte au négatif ?',
    options: [
      'She doesn\'t likes cats.',
      'She don\'t like cats.',
      'She doesn\'t like cats.',
      'She isn\'t like cats.',
    ],
    correctAnswer: "She doesn't like cats.",
    explanation: 'Avec "she/he/it", le négatif se forme avec "doesn\'t" + infinitif (sans -s). Jamais "doesn\'t likes".',
    xpReward: 15,
  },
  // ── A2 : Présent continu ─────────────────────────────────────────────
  {
    id: 'g10',
    type: 'grammar',
    question: 'Complétez : "Look! The children ___ in the garden."',
    options: ['play', 'plays', 'are playing', 'played'],
    correctAnswer: 'are playing',
    explanation: '"Look!" est un signal du présent continu. L\'action est en cours au moment où on parle → "are playing".',
    xpReward: 15,
  },
  {
    id: 'g11',
    type: 'grammar',
    question: 'Quelle phrase utilise INCORRECTEMENT le présent continu ?',
    options: [
      'She is watching TV now.',
      'I am knowing the answer.',
      'They are travelling to Spain.',
      'He is working from home today.',
    ],
    correctAnswer: 'I am knowing the answer.',
    explanation: '"Know" est un verbe d\'état (stative verb). On ne peut pas le mettre au -ing. La forme correcte est "I know the answer".',
    xpReward: 20,
  },
  // ── A2 : Passé simple ────────────────────────────────────────────────
  {
    id: 'g12',
    type: 'grammar',
    question: 'Choisissez la forme correcte au passé : "Yesterday, we ___ to the cinema."',
    options: ['go', 'goes', 'went', 'going'],
    correctAnswer: 'went',
    explanation: '"Go" est un verbe irrégulier. Son passé simple est "went". "Yesterday" indique qu\'il faut utiliser le passé simple.',
    xpReward: 15,
  },
  {
    id: 'g13',
    type: 'grammar',
    question: 'Question correcte au passé simple : "___ you see the match last night?"',
    options: ['Were', 'Did', 'Have', 'Was'],
    correctAnswer: 'Did',
    explanation: 'Pour les questions au passé simple, on utilise "Did" + infinitif (base verbale). "Did you see?" est la structure correcte.',
    xpReward: 15,
  },
  {
    id: 'g14',
    type: 'grammar',
    question: 'Quelle phrase est au passé simple NÉGATIF correctement ?',
    options: [
      'I didn\'t went to school.',
      'I didn\'t go to school.',
      'I not went to school.',
      'I wasn\'t go to school.',
    ],
    correctAnswer: "I didn't go to school.",
    explanation: 'Après "didn\'t", on utilise toujours l\'infinitif (base verbale). "I didn\'t GO" (pas "went").',
    xpReward: 15,
  },
  // ── A2 : Futur ───────────────────────────────────────────────────────
  {
    id: 'g15',
    type: 'grammar',
    question: 'Choisissez : "Look at those dark clouds! It ___ rain."',
    options: ['will', 'is going to', 'goes to', 'shall'],
    correctAnswer: 'is going to',
    explanation: 'On voit des nuages sombres → indice visible → on utilise "going to" pour une prédiction basée sur une preuve concrète.',
    xpReward: 20,
  },
  {
    id: 'g16',
    type: 'grammar',
    question: 'Quelle phrase exprime une DÉCISION SPONTANÉE ?',
    options: [
      'I am going to cook tonight — I already bought ingredients.',
      'I will have a coffee, please. (au serveur)',
      'She is going to start her diet next Monday.',
      'They are going to move to London next year.',
    ],
    correctAnswer: 'I will have a coffee, please. (au serveur)',
    explanation: '"Will" s\'utilise pour une décision prise sur le moment (spontanée). Les autres exemples décrivent des plans prévus à l\'avance → "going to".',
    xpReward: 20,
  },
  // ── A2 : Comparatifs ────────────────────────────────────────────────
  {
    id: 'g17',
    type: 'grammar',
    question: 'Comparatif correct : "Mount Everest is ___ mountain in the world."',
    options: ['the most high', 'higher', 'the highest', 'the most highest'],
    correctAnswer: 'the highest',
    explanation: '"High" est un adjectif court (1 syllabe) → superlatif avec "the + -est". "High → the highest". On ne dit JAMAIS "the most highest".',
    xpReward: 15,
  },
  {
    id: 'g18',
    type: 'grammar',
    question: 'Quelle phrase est CORRECTE ?',
    options: [
      'She is more tall than her sister.',
      'This film is interestinger than that one.',
      'He is more intelligent than his brother.',
      'Paris is beautifuler than Lyon.',
    ],
    correctAnswer: 'He is more intelligent than his brother.',
    explanation: '"Intelligent" a 4 syllabes → comparatif avec "more". Les adjectifs courts (tall, interesting, beautiful) utilisent -er ou more selon leur longueur.',
    xpReward: 20,
  },
  // ── B1 : Present Perfect ────────────────────────────────────────────
  {
    id: 'g19',
    type: 'grammar',
    question: 'Choisissez la bonne forme : "I ___ never ___ sushi before."',
    options: ['have / eaten', 'did / eat', 'had / eaten', 'am / eating'],
    correctAnswer: 'have / eaten',
    explanation: '"Never" avec une expérience de vie → present perfect. "I have never eaten sushi" = je n\'ai jamais mangé de sushi (dans ma vie).',
    xpReward: 20,
  },
  {
    id: 'g20',
    type: 'grammar',
    question: 'Quelle phrase est INCORRECTE ?',
    options: [
      'I have visited London last year.',
      'She has just arrived.',
      'Have you ever been to Spain?',
      'They have already finished the project.',
    ],
    correctAnswer: 'I have visited London last year.',
    explanation: '"Last year" est une date précise dans le passé → il faut le passé simple : "I VISITED London last year". Le present perfect ne s\'utilise pas avec des marqueurs de temps précis.',
    xpReward: 20,
  },
  {
    id: 'g21',
    type: 'grammar',
    question: 'Complétez : "She ___ English for 5 years."',
    options: [
      'learns',
      'has been learning',
      'had learned',
      'is learning',
    ],
    correctAnswer: 'has been learning',
    explanation: 'Action qui a commencé dans le passé et continue jusqu\'à maintenant, avec la durée "for 5 years" → present perfect continuous : "has been learning".',
    xpReward: 20,
  },
  // ── B1 : Passé continu ───────────────────────────────────────────────
  {
    id: 'g22',
    type: 'grammar',
    question: 'Quelle phrase décrit une action INTERROMPUE dans le passé ?',
    options: [
      'I watched TV last night.',
      'I was watching TV when the power went out.',
      'I have watched TV all evening.',
      'I used to watch TV every night.',
    ],
    correctAnswer: 'I was watching TV when the power went out.',
    explanation: '"was/were + -ing" décrit l\'action en cours, "when + simple past" décrit l\'interruption. C\'est la structure classique du passé continu.',
    xpReward: 20,
  },
  // ── B1 : Conditionnel 1 ──────────────────────────────────────────────
  {
    id: 'g23',
    type: 'grammar',
    question: 'Complétez le conditionnel type 1 : "If it ___ tomorrow, we ___ the picnic."',
    options: [
      'will rain / cancel',
      'rains / will cancel',
      'rains / would cancel',
      'rained / will cancel',
    ],
    correctAnswer: 'rains / will cancel',
    explanation: 'Conditionnel type 1 (situation réelle/probable) : "If + présent simple, will + infinitif". Jamais "will" dans la proposition "if".',
    xpReward: 20,
  },
  // ── B1 : Voix passive ────────────────────────────────────────────────
  {
    id: 'g24',
    type: 'grammar',
    question: 'Transformez à la voix passive : "Shakespeare wrote Hamlet."',
    options: [
      'Hamlet was written by Shakespeare.',
      'Hamlet is written by Shakespeare.',
      'Hamlet was wrote by Shakespeare.',
      'Hamlet has been writing by Shakespeare.',
    ],
    correctAnswer: 'Hamlet was written by Shakespeare.',
    explanation: 'Voix passive au passé : "was/were + participe passé". "Write" → participe passé "written". "By Shakespeare" indique l\'auteur de l\'action.',
    xpReward: 20,
  },
  {
    id: 'g25',
    type: 'grammar',
    question: 'Quelle phrase est à la voix passive correcte ?',
    options: [
      'The cake was ate by the children.',
      'The cake was eaten by the children.',
      'The cake is ate by the children.',
      'The cake was eating by the children.',
    ],
    correctAnswer: 'The cake was eaten by the children.',
    explanation: '"Eat" → participe passé irrégulier "eaten". La voix passive : "was/were + V3 (participe passé)".',
    xpReward: 20,
  },
  // ── B2 : Conditionnel 2 ──────────────────────────────────────────────
  {
    id: 'g26',
    type: 'grammar',
    question: 'Complétez le conditionnel type 2 : "If I ___ you, I ___ apologize."',
    options: [
      'am / will',
      'was / would',
      'were / would',
      'was / will',
    ],
    correctAnswer: 'were / would',
    explanation: 'Conditionnel type 2 (imaginaire) : "If + past simple/were, would + infinitif". Avec "I", on préfère "were" (subjonctif) même si "was" est aussi accepté en informel.',
    xpReward: 25,
  },
  {
    id: 'g27',
    type: 'grammar',
    question: 'Conditionnel type 3 correct : "If she ___ the exam, she ___ very happy."',
    options: [
      'passed / will be',
      'had passed / would have been',
      'has passed / would be',
      'would pass / was',
    ],
    correctAnswer: 'had passed / would have been',
    explanation: 'Conditionnel type 3 (irréel dans le passé) : "If + past perfect (had + V3), would have + V3". Elle n\'a PAS réussi → situation hypothétique passée.',
    xpReward: 25,
  },
  // ── B2 : Discours rapporté ────────────────────────────────────────────
  {
    id: 'g28',
    type: 'grammar',
    question: 'Discours rapporté correct : He said "I am tired." →',
    options: [
      'He said he is tired.',
      'He said he was tired.',
      'He said he has been tired.',
      'He said he will be tired.',
    ],
    correctAnswer: 'He said he was tired.',
    explanation: 'Au discours rapporté, les temps reculent d\'un cran : présent simple → passé simple. "am" → "was".',
    xpReward: 25,
  },
  // ── Modaux ────────────────────────────────────────────────────────────
  {
    id: 'g29',
    type: 'grammar',
    question: 'Quel modal exprime une OBLIGATION forte ?',
    options: [
      'You should eat vegetables.',
      'You could eat vegetables.',
      'You must wear a helmet.',
      'You might eat vegetables.',
    ],
    correctAnswer: 'You must wear a helmet.',
    explanation: '"Must" exprime une obligation forte ou une règle impérative. "Should" = conseil, "could/might" = possibilité.',
    xpReward: 15,
  },
  {
    id: 'g30',
    type: 'grammar',
    question: 'Laquelle de ces phrases contient une ERREUR avec les modaux ?',
    options: [
      'She can speak four languages.',
      'You should to see a doctor.',
      'They must leave by 9 PM.',
      'He could swim before he was five.',
    ],
    correctAnswer: 'You should to see a doctor.',
    explanation: 'Les modaux (can, could, should, must, will, would, may, might) ne sont JAMAIS suivis de "to". Correct : "You should SEE a doctor".',
    xpReward: 20,
  },
  // ── Expression écrite ─────────────────────────────────────────────────
  {
    id: 'g31',
    type: 'grammar',
    question: 'Quelle formule de CLÔTURE convient à une lettre formelle adressée à "Dear Sir" ?',
    options: [
      'Yours sincerely,',
      'Yours faithfully,',
      'Best regards,',
      'Take care,',
    ],
    correctAnswer: 'Yours faithfully,',
    explanation: 'Règle d\'or : si vous ne connaissez pas le nom → "Dear Sir/Madam" + "Yours faithfully". Si vous connaissez le nom → "Dear Mr Smith" + "Yours sincerely".',
    xpReward: 20,
  },
  {
    id: 'g32',
    type: 'grammar',
    question: 'Quel connecteur introduit le mieux un CONTRASTE ?',
    options: ['Furthermore', 'Therefore', 'However', 'In addition'],
    correctAnswer: 'However',
    explanation: '"However" (cependant/pourtant) introduit un contraste ou une opposition. "Furthermore/In addition" → addition. "Therefore" → conséquence.',
    xpReward: 15,
  },
  {
    id: 'g33',
    type: 'grammar',
    question: 'Quelle phrase d\'ouverture convient à un EMAIL FORMEL de candidature ?',
    options: [
      'Hey! I want the job.',
      'I am writing to apply for the position of Marketing Manager.',
      'I\'m contacting you because I\'d like the job.',
      'Please find me a job at your company.',
    ],
    correctAnswer: 'I am writing to apply for the position of Marketing Manager.',
    explanation: 'L\'email formel commence par "I am writing to + raison". Les contractions (I\'m) et le ton familier sont à éviter en contexte professionnel.',
    xpReward: 20,
  },
  {
    id: 'g34',
    type: 'grammar',
    question: 'Dans un essai argumentatif, où introduit-on les NOUVELLES idées ?',
    options: [
      'Dans la conclusion uniquement',
      'Dans chaque paragraphe du corps',
      'Uniquement dans l\'introduction',
      'Dans la conclusion et l\'introduction',
    ],
    correctAnswer: 'Dans chaque paragraphe du corps',
    explanation: 'Dans un essai, la conclusion NE doit PAS introduire de nouvelles idées — elle résume et reformule. Les nouvelles idées sont développées dans les paragraphes du corps.',
    xpReward: 20,
  },
  {
    id: 'g35',
    type: 'grammar',
    question: 'Complétez avec le bon connecteur : "___ the rain, the match was cancelled."',
    options: ['Because', 'Due to', 'Therefore', 'However'],
    correctAnswer: 'Due to',
    explanation: '"Due to" (en raison de) est suivi d\'un NOM ou groupe nominal. "Because" est suivi d\'une proposition avec sujet + verbe. "Due to the rain" (nom) est correct ici.',
    xpReward: 20,
  },
];

export const readingExercises: Exercise[] = [
  {
    id: 'r1',
    type: 'reading',
    question: `**Lisez ce texte et répondez :**

*"Hi! My name is Sarah. I'm 25 years old and I live in London. I work as a teacher at a primary school. Every morning, I wake up at 7 AM, have breakfast, and take the subway to work. I love my job because children are very funny and creative. In my free time, I enjoy reading books and going for walks in the park."*

**Question :** À quelle heure Sarah se réveille-t-elle ?`,
    options: ['6h00', '7h00', '8h00', '9h00'],
    correctAnswer: '7h00',
    explanation: 'Le texte dit "I wake up at 7 AM" — elle se réveille à 7h du matin.',
    xpReward: 20,
  },
];

export const listeningExercises: Exercise[] = [
  {
    id: 'li1',
    type: 'listening',
    question: 'Écoutez et choisissez ce que dit le locuteur :',
    options: [
      'The weather is nice today.',
      'The weather is bad today.',
      'The weather was nice yesterday.',
      'I like the weather here.',
    ],
    correctAnswer: 'The weather is nice today.',
    explanation: 'Le locuteur dit "The weather is nice today" — il commente la météo du jour.',
    audioUrl: 'demo',
    xpReward: 20,
  },
];

export const speakingExercises: Exercise[] = [
  {
    id: 'sp1',
    type: 'speaking',
    question: 'Répétez cette phrase à voix haute :',
    correctAnswer: 'Hello, my name is Alex and I am learning English.',
    explanation: 'Excellent travail ! Concentrez-vous sur la prononciation du "th" dans "the" et l\'intonation montante.',
    xpReward: 25,
  },
];

export const leaderboard: LeaderboardEntry[] = [
  { rank: 1, user: { name: 'Marie L.', avatar: 'M', league: 'diamond' }, weeklyXP: 1240 },
  { rank: 2, user: { name: 'Pierre D.', avatar: 'P', league: 'diamond' }, weeklyXP: 1180 },
  { rank: 3, user: { name: 'Sophie B.', avatar: 'S', league: 'gold' }, weeklyXP: 980 },
  { rank: 4, user: { name: 'Thomas R.', avatar: 'T', league: 'gold' }, weeklyXP: 890 },
  { rank: 5, user: { name: 'Emma V.', avatar: 'E', league: 'gold' }, weeklyXP: 820 },
  { rank: 6, user: { name: 'Alexandre', avatar: 'A', league: 'gold' }, weeklyXP: 580, isCurrentUser: true },
  { rank: 7, user: { name: 'Lucas M.', avatar: 'L', league: 'silver' }, weeklyXP: 540 },
  { rank: 8, user: { name: 'Chloé P.', avatar: 'C', league: 'silver' }, weeklyXP: 490 },
  { rank: 9, user: { name: 'Hugo F.', avatar: 'H', league: 'silver' }, weeklyXP: 430 },
  { rank: 10, user: { name: 'Léa N.', avatar: 'L', league: 'bronze' }, weeklyXP: 380 },
];

export const languageInfo = {
  english: {
    name: 'Anglais',
    flag: '🇬🇧',
    nativeName: 'English',
    color: '#3B82F6',
    gradient: 'from-blue-600 to-cyan-500',
    speakers: '1.5 milliard',
    difficulty: 'Facile',
  },
  spanish: {
    name: 'Espagnol',
    flag: '🇪🇸',
    nativeName: 'Español',
    color: '#EF4444',
    gradient: 'from-red-600 to-orange-500',
    speakers: '500 millions',
    difficulty: 'Facile',
  },
  portuguese: {
    name: 'Portugais',
    flag: '🇧🇷',
    nativeName: 'Português',
    color: '#10B981',
    gradient: 'from-emerald-600 to-teal-500',
    speakers: '250 millions',
    difficulty: 'Moyen',
  },
};

export const streakCalendar = Array.from({ length: 30 }, (_, i) => ({
  day: i + 1,
  hasActivity: i < 12 && i !== 4 && i !== 9,
  xp: i < 12 ? Math.floor(Math.random() * 100) + 20 : 0,
}));
